# Generated by Django 2.2.7 on 2019-11-26 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=15, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=15, verbose_name='apellido_materno')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('saldo', models.IntegerField(default=0, verbose_name='saldo')),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_modificacion', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(blank=True, default='B', max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='favoritos',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Libro')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Public.login')),
            ],
            options={
                'db_table': 'favoritos',
            },
        ),
        migrations.CreateModel(
            name='compraR',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Public.login')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Revista')),
            ],
            options={
                'db_table': 'compraR',
            },
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Libro')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Public.login')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=1000, verbose_name='texto')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Libro')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Public.login')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
    ]
