# Generated by Django 2.2.7 on 2019-11-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos_autor', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('nacionalidad_autor', models.CharField(blank=True, max_length=180, verbose_name='Nacionalidad')),
                ('fecha_creacion_autor', models.DateField()),
                ('fecha_modificacion_autor', models.DateField()),
                ('status_autor', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=180, verbose_name='Nombre')),
                ('descripcion_categoria', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('fecha_creacion_categoria', models.DateField()),
                ('fecha_modificacion_categoria', models.DateField()),
                ('status_categoria', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(max_length=180, verbose_name='Nombre')),
                ('pais_editorial', models.CharField(max_length=300, verbose_name='Pais')),
                ('fecha_creacion_editorial', models.DateField()),
                ('fecha_modificacion_editorial', models.DateField()),
                ('status_editorial', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'Editorial',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion_servicio', models.CharField(max_length=180, verbose_name='Descripcion')),
                ('fecha_creacion_servicio', models.DateField()),
                ('fecha_modificacion_servicio', models.DateField()),
                ('status_servicio', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, verbose_name='Username')),
                ('password', models.CharField(max_length=80, verbose_name='Paswword')),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('status', models.CharField(blank=True, max_length=1, verbose_name='Status')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=180, verbose_name='Nombre')),
                ('descripcion_sucursal', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('telefono_sucursal', models.CharField(max_length=10, verbose_name='Telefono')),
                ('fecha_creacion_sucursal', models.DateField()),
                ('fecha_modificacion_sucursal', models.DateField()),
                ('status_sucursal', models.CharField(max_length=1, verbose_name='status')),
                ('servicio', models.ManyToManyField(blank=True, to='Administracion.Servicios')),
            ],
            options={
                'db_table': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id_revista', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_revista', models.CharField(max_length=80, verbose_name='Nombres')),
                ('no_paginas_revista', models.IntegerField(verbose_name='Paginas')),
                ('fecha_creacion_revista', models.DateField()),
                ('fecha_modificacion_revista', models.DateField()),
                ('costo', models.IntegerField(default=0, verbose_name='costo')),
                ('status_revista', models.CharField(max_length=1, verbose_name='status')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Categoria')),
                ('sucursal', models.ManyToManyField(blank=True, to='Administracion.Sucursales')),
            ],
            options={
                'db_table': 'Revista',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_libro', models.CharField(max_length=80, verbose_name='Nombres')),
                ('no_paginas_libro', models.IntegerField(verbose_name='Paginas')),
                ('fecha_creacion_libro', models.DateField()),
                ('fecha_modificacion_libro', models.DateField()),
                ('vistas', models.IntegerField(blank=True, verbose_name='vistas')),
                ('costo', models.IntegerField(default=0, verbose_name='costo')),
                ('sinopsis', models.CharField(default='o', max_length=1000, verbose_name='sinopsis')),
                ('status_libro', models.CharField(max_length=1, verbose_name='status')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Editorial')),
                ('sucursal', models.ManyToManyField(blank=True, to='Administracion.Sucursales')),
            ],
            options={
                'db_table': 'Libro',
            },
        ),
        migrations.CreateModel(
            name='codigoAdmin',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6, verbose_name='codigo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Usuario')),
            ],
            options={
                'db_table': 'codigoAdmin',
            },
        ),
    ]
